language: node_js
addons:
  sauce_connect:
    username: "balmas"
    access_key: "ae469ad7-eaf1-4c87-b165-c3f32d27d64a"
before_install: npm install -g grunt-cli
before_script:
  - grunt server &
  - sleep 2
install: npm install && grunt install
